### ISSUE TITLE
"not supported" error thrown when trying the test document.

### ISSUE THREAD

**Issue by NicolasBonet** [prescottprue/cypress-firebase#212]
**Describe the bug**

I'm getting an error trying to create the test document on Firebase

**To Reproduce**

**Expected behavior/code**
I followed all steps, but I'm getting the error attached below which says:

```not supported```

In the protobufjs dependency.

**Possible Solution**

I don't know, I've checked all the opened bugs but cannot find it.

**Additional Context/Screenshots**

![image](https://user-images.githubusercontent.com/13696500/97235709-71c02480-17b1-11eb-8668-4930ccfc3336.png)

Track:

```at Root.loadSync (webpack:///node_modules/protobufjs/src/root.js:246:1)
    at Object.loadSync (webpack:///node_modules/protobufjs/src/index-light.js:69:1)
    at Object.eval (webpack:///node_modules/@grpc/proto-loader/build/src/index.js:230:1)
    at Object../node_modules/@grpc/proto-loader/build/src/index.js (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:58772:31)
    at __webpack_require__ (webpack:///webpack/bootstrap:19:1)
    at Object.eval (webpack:///node_modules/@firebase/firestore/dist/index.node.cjs.js:11:19)
    at Object../node_modules/@firebase/firestore/dist/index.node.cjs.js (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:45894:31)
    at __webpack_require__ (webpack:///webpack/bootstrap:19:1)
    at Object../node_modules/firebase/firestore/dist/index.cjs.js (webpack:///node_modules/firebase/firestore/dist/index.cjs.js:3:1)
    at __webpack_require__ (webpack:///webpack/bootstrap:19:1)
From previous event:
    at Object.runScripts (http://localhost:3000/__cypress/runner/cypress_runner.js:176896:97)
    at $Cypress.onSpecWindow (http://localhost:3000/__cypress/runner/cypress_runner.js:166807:19)```

**Comment by lolcookie** [comment]
What was the fix?

**Comment by prescottprue** [comment]
@lolcookie To receive better support please provide a full repo in a new issue
