### ISSUE TITLE
Unexpected error with new version 0.2

### ISSUE THREAD

**Issue by raulingg** [prescottprue/cypress-firebase#33]
```
"Error with set at path "cohorts/lim-2019-07-pre-core-admission":  Error: @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0
    at Object.<anonymous> (/home/raulingg/Projects/laboratoria/admission.laboratoria.la/node_modules/@grpc/grpc-js/build/src/index.js:45:11)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/raulingg/Projects/laboratoria/admission.laboratoria.la/node_modules/google-gax/build/src/grpc.js:37:14)
    at Module._compile (module.js:653:30)
(node:25453) ExperimentalWarning: The http2 module is an experimental API.
(node:25453) UnhandledPromiseRejectionWarning: Error: @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0
    at Object.<anonymous> (/home/raulingg/Projects/laboratoria/admission.laboratoria.la/node_modules/@grpc/grpc-js/build/src/index.js:45:11)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/raulingg/Projects/laboratoria/admission.laboratoria.la/node_modules/google-gax/build/src/grpc.js:37:14)
    at Module._compile (module.js:653:30)
(node:25453) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:25453) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."

```
![Screenshot from 2019-07-09 18-12-33](https://user-images.githubusercontent.com/9435850/60929026-3ecce700-a275-11e9-886e-b0648a36c86f.png)

my `package.json` 

```json
"devDependencies": {
    "babel-core": "^6.26.0",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^23.0.1",
    "babel-loader": "^7.1.1",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-polyfill": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "clean-webpack-plugin": "^0.1.18",
    "cross-env": "^5.2.0",
    "css-loader": "^0.28.9",
    "cypress": "^3.3.1",
    "cypress-firebase": "^0.2.0",
    "dotenv-webpack": "^1.7.0",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "eslint": "^4.18.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-babel": "^5.3.0",
    "eslint-plugin-chai-friendly": "^0.4.1",
    "eslint-plugin-cypress": "^2.2.1",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.6.1",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "favicons-webpack-plugin": "^0.0.9",
    "file-loader": "^1.1.7",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "husky": "^2.4.1",
    "jest": "^23.1.0",
    "minimist": "^1.2.0",
    "mocha": "^5.2.0",
    "mochawesome": "^4.0.1",
    "mochawesome-merge": "^2.0.1",
    "mochawesome-report-generator": "^4.0.0",
    "uglifyjs-webpack-plugin": "^1.2.0",
    "url-loader": "^1.0.1",
    "webpack": "^4.12.0",
    "webpack-cli": "^3.0.4",
    "webpack-dev-server": "^3.1.4"
  }
```

I need to say that it works fine with the previous version.

**Comment by prescottprue** [comment]
What version of nodejs are you using? Newer versions drop support for older versions of node

**Comment by prescottprue** [comment]
Can you confirm it is due to older node version?
