### ISSUE TITLE
Unexpected DEADLINE_EXCEEDED error

### ISSUE THREAD

**Issue by raulingg** [prescottprue/cypress-firebase#34]
error trace
```
cypress_runner.js:172390 Error: the string "(node:5185) UnhandledPromiseRejectionWarning: Error: 4 DEADLINE_EXCEEDED: Deadline Exceeded\n    at Object.exports.createStatusError (/home/raulingg/Projects/laboratoria/admission.laboratoria.la/node_modules/grpc/src/common.js:91:15)\n    at Object.onReceiveStatus (/home/raulingg/Projects/laboratoria/admission.laboratoria.la/node_modules/grpc/src/client_interceptors.js:1204:28)\n    at InterceptingListener._callNext (/home/raulingg/Projects/laboratoria/admission.laboratoria.la/node_modules/grpc/src/client_interceptors.js:568:42)\n    at InterceptingListener.onReceiveStatus (/home/raulingg/Projects/laboratoria/admission.laboratoria.la/node_modules/grpc/src/client_interceptors.js:618:8)\n    at callback (/home/raulingg/Projects/laboratoria/admission.laboratoria.la/node_modules/grpc/src/client_interceptors.js:845:24)\n(node:5185) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)\n(node:5185) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code." was thrown, throw an Error :)
    at Runner.fail (cypress_runner.js:51724)
    at Runner.fail (cypress_runner.js:81207)
    at cypress_runner.js:52042
    at next (cypress_runner.js:82124)
    at cypress_runner.js:82136
    at tryCatcher (cypress_runner.js:132142)
    at Promise._settlePromiseFromHandler (cypress_runner.js:130160)
    at Promise._settlePromise (cypress_runner.js:130217)
    at Promise._settlePromise0 (cypress_runner.js:130262)
    at Promise._settlePromises (cypress_runner.js:130341)
    at Promise._fulfill (cypress_runner.js:130286)
    at Promise._resolveCallback (cypress_runner.js:130080)
    at Promise._settlePromiseFromHandler (cypress_runner.js:130172)
    at Promise._settlePromise (cypress_runner.js:130217)
    at Promise._settlePromise0 (cypress_runner.js:130262)
    at Promise._settlePromises (cypress_runner.js:130341)
```
![Screenshot from 2019-07-09 18-46-24](https://user-images.githubusercontent.com/9435850/60930245-62466080-a27a-11e9-9866-a74a3d23d031.png)

my `devdependencies`:

```json
"dependencies": {
    "@octokit/rest": "^15.8.2",
    "@typeform/embed": "^0.8.1",
    "axios": "^0.18.0",
    "blueimp-md5": "^2.10.0",
    "brace": "^0.11.1",
    "classnames": "^2.2.5",
    "firebase": "^5.0.4",
    "material-ui": "^1.0.0-beta.34",
    "material-ui-icons": "^1.0.0-beta.17",
    "prismjs": "^1.16.0",
    "prop-types": "^15.6.0",
    "query-string": "^6.2.0",
    "react": "^16.4.0",
    "react-ace": "^7.0.1",
    "react-dom": "^16.4.0",
    "react-ga": "^2.4.1",
    "react-hot-loader": "^4.3.1",
    "react-hotjar": "^2.0.0",
    "react-intl": "^2.4.0",
    "react-redux": "^5.0.7",
    "react-redux-firebase": "2.2.4",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^4.0.8",
    "recompose": "^0.30.0",
    "redux": "^4.0.0",
    "redux-firestore": "^0.5.6",
    "redux-thunk": "^2.3.0"
  },
```

I need to say this error just happens sometimes rarely.

**Comment by prescottprue** [comment]
Not sure what version of `cypress-firebase` you are using. Could you try updating to the newest version and see if this is still happening?

**Comment by prescottprue** [comment]
Thanks for reporting! This has not been able to be reproduced. Please try out the newest latest (v1.0.0 which was just released) and see if you are still experiencing the issue
